language: java
dist: focal
os: linux
jdk:
#  - oraclejdk8
  - openjdk11
git:
  submodules: false
before_install:
  - sudo apt-get update && sudo apt-get install git-core
  - git config --global user.email "travis-ci@travis-ci.com"
  - git config --global user.name "Travis CI"
  - ./paper patch
cache:
  directories:
    - '$HOME/.m2/repository'
    - 'work/Minecraft'
